[functions]
directory = "functions"
node_bundler = "esbuild"

[[edge_functions]]
function = "people"
path = "/api/people"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[build]
command = "npm run build"
publish = "dist/kw-angular-contact-book/browser"
edge_functions = "functions/edge-functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
headers = { Access-Control-Allow-Origin = "*" }

[[redirects]]
from = "/api/people"
to = "functions/edge_functions/people"
status = 200
headers = { Access-Control-Allow-Origin = "*" }